### PR TITLE
Use (wiki.)mirahezebots.org

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by MacFan4000** [comment]
@Universal-Omega there is a merge conflict

**Comment by Universal-Omega** [comment]
> @Universal-Omega there is a merge conflict

Resolved

**Comment by Universal-Omega** [comment]
> > @Universal-Omega there is a merge conflict
> 
> Resolved

Wait nevermind that didn't work right.

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
sitemap.xml diff looks wrong

**Comment by Universal-Omega** [comment]
> sitemap.xml diff looks wrong

Fixed

**Review by RhinosF1 — APPROVED** [review]

**Pull request merged**
